# Generated by Django 3.1.7 on 2021-04-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transNo', models.IntegerField(max_length=100)),
            ],
        ),
    ]
