# Generated by Django 3.1.7 on 2021-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210402_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spareprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transno', models.IntegerField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
