# Generated by Django 3.1.7 on 2021-04-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_spareprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='spare',
            name='partname',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='spare',
            name='qty',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
